spring:
  mail:
    host: smtp.163.com
    username: m17364550730@163.com
    password: hupeng1119
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
server:
  port: 7977