server:
  port: 8000
#打印日志
logging:
  level:
    com:
      hup: debug

spring:
  application:
    name: gateway-server
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    gateway:
      routes:
      - id: ucenter
        uri: lb://ucenter-server
        predicates:
        - Path=/ucenter/**


ribbon:
  ReadTimeout: 300000
  ConnectTimeout: 30000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

#Spring Boot 2.0 的Actuator只暴露了health和info端点，其它的一堆怎么也打不开；下面配置是打开所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

